/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Truco21cartas.Carta;
import Truco21cartas.Mazo;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author agustin
 */
public class testArrayCartas extends javax.swing.JFrame {

    /**
     * Creates new form testArrayCartas
     */
    private ArrayList<Carta> l;
    public testArrayCartas() {
        initComponents();
        JButton button = new JButton("Click for more"); 
        JButton button2 = new JButton("lalala"); 
        //JLabel label = new JLabel("Hola");
        
        
        
        Mazo m = new Mazo();
        m.mazoSinComodin();
        li=(ArrayList<Carta>) m.getMazoSC();
        Truco21cartas.ExTRuco e = new Truco21cartas.ExTRuco();
        ArrayList<ArrayList<Carta>> a = new ArrayList<ArrayList<Carta>>();
        e.vaciar();
        a=e.truco();
        
        
        int j,k;
        ImageIcon i;
        JLabel label;
        for(k=0;k<3;k++)
            {
            for(j=0;j<7;j++)   
                {
                    i = new ImageIcon(getClass().getResource(a.get(k).get(j).getImg()));
                    label = new JLabel(i);
                    add(label);
                    label.setSize(74, 98);
                    label.setLocation(0+k*80, 0+j*100);
                }
            }
        setSize(800, 750);    
        
        //add(button);
        //add(button2);
        //add(label);
        setLayout(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        //button.setLayout(null);
        //button.setLocation(100,100);
        //button.setSize(200,100);
        //label.setLayout(null);
        //label.setLocation(200, 300);
        //label.setSize(100, 50);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    private static testArrayCartas a;
    private static ArrayList<Carta> li;
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testArrayCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testArrayCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testArrayCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testArrayCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                a = new testArrayCartas();
                a.setVisible(true);
                Mazo m = new Mazo();
                m.mazoSinComodin();
                li=(ArrayList<Carta>) m.getMazoSC();
                //a.add(new JLabel(new ImageIcon("b/c10.JPG")));
                a.add(new JLabel("b/c10.JPG"));
                a.repaint();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
